### ISSUE TITLE
App layout doesn't support different screen sizes

### ISSUE THREAD

**Issue by braydentang1** [UBC-MDS/DSCI_532_L02_group207_dashboards#22]
Currently, the layout of the app looks off for my screen and Sirine's. See the photo below:

![Screenshot from 2019-11-28 12-56-47](https://user-images.githubusercontent.com/40974987/69831579-cf817080-11de-11ea-99a9-e37cce8d5831.png)

**Comment by vanandsh** [comment]
App is rendering fine on all screen sizes now.
