### ISSUE TITLE
Changes for compatibility

### ISSUE THREAD

**Issue by braydentang1** [UBC-MDS/DSCI_532_L02_group207_dashboards#25]
- Change the radio buttons to a dropdown menu for year
- Resize the "faceted" graph, width = 200, height = 230 is confirmed to be working
- Switch the axis orientation for the "faceted" graph
- Switch the color of the graph

I think that is what we discussed.

**Comment by vanandsh** [comment]
This has been fixed except year menu - sticking to radio buttons for now.
