### ISSUE TITLE
Lab Feedback

### ISSUE THREAD

**Issue by schepal** [UBC-MDS/DSCI_532_L02_group207_dashboards#38]
- Side bar has nice aesthetics and a clean layout
- Providing a better description on the context for the plot could have been more clear. For example, it could be useful to include a title for the map (ie: where it is located in the USA).
- Also - providing a small blurb on the purpose and background on the plot could make it easier for individuals not familiar with this data set to understand the plot.
- Text labels could be bigger to make it easier to read.

Overall, nice and simple charts are easy to follow - just provide a bit more detail on what you are trying to achieve with them.

**Comment by vanandsh** [comment]
Thanks for the feedback. The issue has been merged with another issue that tracks these changes - https://github.com/UBC-MDS/DSCI_532_L02_group207_dashboards/issues/41
