### ISSUE TITLE
Lab Feedback

### ISSUE THREAD

**Issue by matc84** [UBC-MDS/DSCI_532_L02_group207_dashboards#39]
It's unclear what this map is and what the red dots are. Consider adding labels to the map.

Consider adding a summary to the dashboard so that the user has a little more information.

The side to side scrolling is a little problematic.

Cities/farms on map could be labeled.

Multiple selector is cool, unsure what they’re doing. The dropdown is a little confusing, maybe try checkboxes.

Side by side bar charts could be more useful.

Tooltips on the map are very nice!

Think about disabling the interactivity; people will accidentally scroll on your charts.

Great job!

**Comment by vanandsh** [comment]
Thanks for the feedback. The issue has been merged with another issue that tracks these changes -https://github.com/UBC-MDS/DSCI_532_L02_group207_dashboards/issues/41
