### ISSUE TITLE
Feedback...Great job !!

### ISSUE THREAD

**Issue by amank90** [UBC-MDS/DSCI_532_L02_group207_dashboards#40]
- Saw white lines on the yield per variety and yield per site plots and was not sure what they implied.
- The map at the top of the dashboard doesn't make too much sense. It can be moved to the side of the dashboard with a proper title.
- Some textual description is required. Like why is the data for 1931 and 1932. Is there a specific reason for this?

**Comment by vanandsh** [comment]
Thank you for the feedback. The suggestions are being tracked in another issue - https://github.com/UBC-MDS/DSCI_532_L02_group207_dashboards/issues/41
