### ISSUE TITLE
Layout of the app with descriptions

### ISSUE THREAD

**Issue by braydentang1** [UBC-MDS/DSCI_532_L02_group207_dashboards#44]
Right now, I think that the layout needs to be fixed.

The text that describes the data (like the header at the top) should be made to look distinct from the graphs
The text is way too big in the toolbar where everything is selected
"Map of the location of selected sites" (the title) should reference Minnesota directly
The text describing the plots is good in my opinion.

**Comment by vanandsh** [comment]
All of this has been fixed in the later commits. 

- Text size reduced
- Minnesota highlighted in the description
- Moved graph descriptions to tooltip
